version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  mock-exporter:
    build:
      context: .
    container_name: mock-exporter
    ports:
      - "9001:9000"
    depends_on:
      - prometheus

  backend:
    build:
      context: ./flask
    container_name: flask-backend
    ports:
      - "5000:5000"
    depends_on:
      - prometheus
